# Generated by Django 4.0 on 2022-11-03 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('true_answer', models.CharField(max_length=64)),
                ('false_answer1', models.CharField(max_length=64)),
                ('false_answer2', models.CharField(max_length=64)),
                ('false_answer3', models.CharField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.category')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=24)),
                ('is_finished', models.BooleanField(default=False)),
                ('total_score', models.IntegerField(default=0)),
                ('current_question_index', models.IntegerField(default=0)),
                ('total_number_of_questions', models.IntegerField(default=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.category')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.pet')),
                ('questionset', models.ManyToManyField(to='quiz.Question')),
            ],
        ),
    ]
