# Generated by Django 4.0 on 2022-10-31 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('true_answer', models.CharField(max_length=64)),
                ('false_answer1', models.CharField(max_length=64)),
                ('false_answer2', models.CharField(max_length=64)),
                ('false_answer3', models.CharField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.category')),
            ],
        ),
    ]
