# Generated by Django 4.0 on 2022-11-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_question_nr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='total_questions_nr',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='game',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
